travis:
  secure:
    BINSTAR_TOKEN: YKuEL2Dt/RG6OrgDKm2FwfAlrIF6yjS3ks4GfcoT6yV/ozo/BKJ9+aq9l4TcNN0vyTvzCb49jFAbmVqyRSAtvzVRRMuol5YUq0CJsl+nK2NUgZQZ8bmSERilvhSQfv/Kol3yYyn/jO1FDE/qGBgm/L92O1OgjAOfSosNt2N9grF53nVtME5XAedGIIm8/tftNtqY9cLWr+SYHj1l4Pz7DVxwkNjJ5qVvvrBTAhjeGICkuNlBoG+1azqbsIb5zW24BUYqO6OiROQw5Vejv0Y9+wwcT/Swjcr4inH1sTUlxrnqo4AUi/VrdE20ubRq+QZ9bn+xoKDMfEG4KUOYUykHc746hEMfRIYhMItJBBp+9+w4qCZCXGNFyXolzr0xyNv1nMJVszplsrfw7knDGtxV8phmJ7yr0IfFzgyeNSjUjZTbhmeI8Cx60uyFIw4xmVu36+MtgsMxZWrifclpELVnPSndAQNQJOUS0pRNGdP45HiU09JdAkpPbRx3GNJW3zIsQFOHeWlwd8r3gp6D1PfUic+/qtWVDDyErCb0MRQxvck8KdBJGMdLf7iGlZJgYbhA5Ew1EL89lwzD+G9w1M+ky/S07u9DGcz3bf7f5PKggtXsOqWNCkOe23A8v1FMGkm/gYPXukF412sHCHUjGSkLCDYSsgThG2WWVGtYklil2js=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
